# Generated by Django 6.0 on 2025-12-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'General Manager'), ('OPS', 'Operations Manager'), ('ADM_MANAGER', 'Admission Manager'), ('ADM_EXEC', 'Admission Executive'), ('PROCESSING', 'Processing Executive'), ('MEDIA', 'Media Team'), ('TRAINER', 'Trainer'), ('BUSINESS_HEAD', 'Business Head'), ('BDM', 'Business Development Manager'), ('CM', 'Center Manager'), ('HR', 'Human Resources'), ('FOE', 'FOE Cum TC')], db_index=True, max_length=100),
        ),
    ]
