# Generated by Django 6.0 on 2025-12-26 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('status', models.TextField(default='ENQUIRY', help_text='Current status of the lead')),
                ('program', models.CharField(blank=True, help_text='Enter the program name', max_length=2000, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or comments about the lead', null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Website'), ('WALK_IN', 'Walk-in'), ('AUTOMATION', 'automation'), ('OTHER', 'Other')], max_length=10)),
                ('custom_source', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded to Processing'), ('ACCEPTED', 'Accepted by Processing'), ('PROCESSING', 'In Processing'), ('COMPLETED', 'Processing Completed'), ('REJECTED', 'Processing Rejected')], default='PENDING', max_length=20)),
                ('processing_status_date', models.DateTimeField(auto_now_add=True)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('document_status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('VERIFIED', 'Verified'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('documents_received', models.TextField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded to Processing'), ('ACCEPTED', 'Accepted by Processing'), ('PROCESSING', 'In Processing'), ('COMPLETED', 'Processing Completed'), ('REJECTED', 'Processing Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RemarkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_remarks', models.TextField(blank=True, null=True)),
                ('new_remarks', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
