# Generated by Django 6.0 on 2025-12-22 17:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('status', models.TextField(default='ENQUIRY', help_text='Current status of the lead')),
                ('program', models.CharField(blank=True, help_text='Enter the program name', max_length=2000, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or comments about the lead', null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Website'), ('WALK_IN', 'Walk-in'), ('AUTOMATION', 'automation'), ('OTHER', 'Other')], max_length=10)),
                ('custom_source', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded to Processing'), ('ACCEPTED', 'Accepted by Processing'), ('PROCESSING', 'In Processing'), ('COMPLETED', 'Processing Completed'), ('REJECTED', 'Processing Rejected')], default='PENDING', max_length=20)),
                ('processing_status_date', models.DateTimeField(auto_now_add=True)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('document_status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('VERIFIED', 'Verified'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('documents_received', models.TextField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADM_MANAGER', 'ADM_EXEC']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('processing_executive', models.ForeignKey(blank=True, limit_choices_to={'role': 'PROCESSING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded to Processing'), ('ACCEPTED', 'Accepted by Processing'), ('PROCESSING', 'In Processing'), ('COMPLETED', 'Processing Completed'), ('REJECTED', 'Processing Rejected')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_updates', to='leads.lead')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RemarkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_remarks', models.TextField(blank=True, null=True)),
                ('new_remarks', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark_history', to='leads.lead')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority'], name='leads_lead_priorit_ddce28_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['processing_status'], name='leads_lead_process_39b111_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='leads_lead_assigne_3f8857_idx'),
        ),
    ]
