# Generated by Django 6.0 on 2025-12-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='processing_status_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='program',
            field=models.TextField(blank=True, help_text='Enter the program name', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Website'), ('WALK_IN', 'Walk-in'), ('AUTOMATION', 'Automation'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('phone', 'email')},
        ),
    ]
