# Generated by Django 6.0 on 2026-01-17 05:00

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Document Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('month', models.CharField(max_length=100, verbose_name='Month')),
                ('document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Attendance Document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Document',
                'verbose_name_plural': 'Attendance Documents',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(max_length=1000, verbose_name='Reason / Act')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month', models.CharField(max_length=100, verbose_name='Month')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
                'ordering': ['-date'],
            },
        ),
    ]
