# Generated by Django 6.0 on 2026-01-17 04:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Document Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('month', models.CharField(max_length=100, verbose_name='Month')),
                ('document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Attendance Document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Document',
                'verbose_name_plural': 'Attendance Documents',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('join_date', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('penalty', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(max_length=1000)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('month', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Penalty',
                'verbose_name_plural': 'Penalties',
                'ordering': ['-date'],
            },
        ),
    ]
