# Generated by Django 6.0 on 2026-01-15 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['user', 'report_date'], name='reports_dai_user_id_ac4ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['status', 'report_date'], name='reports_dai_status_13cf8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('user', 'report_date')},
        ),
    ]
